config/routes.rb
# frozen_string_literal: true

Lecter::Engine.routes.draw do
  root 'diagnosis#new'

  resource :diagnosis, only: %w[new create show], controller: :diagnosis
end

app/controllers/lecter/diagnosis_controller.rb
# frozen_string_literal: true

module Lecter
  class DiagnosisController < ActionController::Base
    layout 'lecter'
    before_action :format_request_data, only: :create

    def new; end

    def show
      redirect_to new_diagnosis_path
    end

    def create
      requester = Lecter::Requester.new(requester_params)
      if requester.call
        @file_listings = HtmlGenerator.new(requester.lines).call
        render :show
      else
        flash[:error] = requester.error_message
        render :new
      end
    end

    private

    def diagnosis_params
      params.permit(:endpoint, :body_raw, :method, :headers)
    end

    def requester_params
      {
        method: diagnosis_params[:method].downcase.to_sym,
        url: diagnosis_params[:endpoint],
        payload: formatter_payload.result,
        headers: formatted_headers.result
      }
    end

    def format_request_data
      formatters = [formatter_payload, formatted_headers]
      return if formatters.all?(&:call)

      flash[:error] = formatters.map(&:error_message).join(', ')
      render :new
    end

    def formatter_payload
      @formatter_payload ||= Lecter::FormatterPayload.new(diagnosis_params[:body_raw])
    end

    def formatted_headers
      @formatted_headers ||= Lecter::FormatterHeaders.new(diagnosis_params[:headers])
    end
  end
end

app/views/layouts/lecter.html.erb
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= javascript_include_tag '//code.jquery.com/jquery-1.12.4.js', '//code.jquery.com/ui/1.12.1/jquery-ui.js' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css' %>
  </head>

  <style>
    .hljs {
        display: block;
        overflow-x: auto;
        padding: 0.5em;
        background: #232323;
        color: #e6e1dc;
    }

    .hljs-comment,
    .hljs-quote {
        color: #bc9458;
        font-style: italic;
    }

    .hljs-keyword,
    .hljs-selector-tag {
        color: #c26230;
    }

    .hljs-string,
    .hljs-number,
    .hljs-regexp,
    .hljs-variable,
    .hljs-template-variable {
        color: #a5c261;
    }

    .hljs-subst {
        color: #519f50;
    }

    .hljs-tag,
    .hljs-name {
        color: #e8bf6a;
    }

    .hljs-type {
        color: #da4939;
    }


    .hljs-symbol,
    .hljs-bullet,
    .hljs-built_in,
    .hljs-builtin-name,
    .hljs-attr,
    .hljs-link {
        color: #6d9cbe;
    }

    .hljs-params {
        color: #d0d0ff;
    }

    .hljs-attribute {
        color: #cda869;
    }

    .hljs-meta {
        color: #9b859d;
    }

    .hljs-title,
    .hljs-section {
        color: #ffc66d;
    }

    .hljs-addition {
        background-color: #144212;
        color: #e6e1dc;
        display: inline-block;
        width: 100%;
    }

    .hljs-deletion {
        background-color: #600;
        color: #e6e1dc;
        display: inline-block;
        width: 100%;
    }

    .hljs-selector-class {
        color: #9b703f;
    }

    .hljs-selector-id {
        color: #8b98ab;
    }

    .hljs-emphasis {
        font-style: italic;
    }

    .hljs-strong {
        font-weight: bold;
    }

    .hljs-link {
        text-decoration: underline;
    }

    /* diagnosis/show.slim */


    .down {
        border-left: 5px solid transparent;
        border-right: 5px solid transparent;
        border-top: 5px solid black;
        margin: 10px 7px 0 5px;
    }

    .ui-accordion .ui-accordion-header {
        font-size: 78%;
    }

    .sidebar {
        float: left;
    }

    .sidebar > .sidebar-wrapper {
        width: 235px;
        position: fixed;
        margin: 49px 33px 0 0;
        overflow-y: scroll;
        top: 82px;
        bottom: 40px;
    }

    .sidebar-wrapper > ul {
        list-style-type: none;
        height: calc(100% - 40px);
    }

    .sidebar-wrapper > ul > li {
        margin-bottom: 3px;
    }

    .sidebar-wrapper > ul > li > a {
        text-decoration: none;
        color: inherit;
        display: block;
        font-size: 13px;
        text-inline: 1.5;
    }

    .sidebar-wrapper > ul > li > a:hover {
        color: #7d7d7d;
    }

    .right {
        float: left;
        padding-left: 10px;
        width: 70%;
        margin-left: 295px;
    }

    .listing {
        display: none;
        padding: 1em 2.2em;
        overflow: auto;
        border-bottom-right-radius: 4px;
        border: 0.5px solid;
        border-top-width: 0;
        border-bottom-left-radius: 4px;
        background: #efefef;
    }

    .filename {
        cursor: pointer;
        position: relative;
        margin: 2px 0 0 0;
        padding: .5em .5em .5em .7em;
        border: solid 0.1px;
        background: #efefef;
    }

    /* layouts/lecter.slim */

    body {
        font-family: "Helvetica Neue", "Helvetica", Arial, "Open Sans", sans-serif;
        font-size: 15px;
        line-height: 1.6;
        -webkit-font-smoothing: antialiased;
    }

    .body-wrapper {
        overflow: hidden;
        *zoom: 1;
        margin-top: 50px;
        margin-bottom: 50px;
        display: block;
        padding: 0 20px;
    }

    .nav {
        font-weight: 500;
        background: #0b4e22;
        border-bottom: 1px solid #cccccc;
    }

    .nav-inner {
        display: block;
        max-width: 955px;
        padding: 1px 20px;
    }

    .nav-inner > ul {
        list-style-type: none;
    }

    .nav-inner > ul > li > a {
        text-decoration: none;
        font-weight: 600;
        color: white;
        letter-spacing: 0.4px;
    }

    .ul {
        -webkit-justify-content: space-between;
        justify-content: space-between;
        list-style-type: none;
        margin: 0;
        padding: 8px 2px 8px;
        display: -webkit-flex;
        display: flex;
    }

    .li {
        -webkit-flex: 0 1 auto;
        flex: 0 1 auto;
        display: list-item;
        text-align: -webkit-match-parent;
        list-style-type: none;
    }

    .nav-inner > li > a {
        text-decoration: none;
        font-weight: 400;
        color: white;
        letter-spacing: 0.4px;
    }
  </style>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lecter/diagnosis/new.erb
<%= content_for :title, t('.title')  %>

<h1><%= t('.title') %></h1>

<%= form_tag diagnosis_path do %>
  <% flash.each do |key, value| %>
    <%= value %>
  <% end %>
  <% %i[endpoint params].each do |attr|  %>
    <p>
      <%= label_tag t(".#{attr}") %>
      <%= text_field_tag attr %>
    </p>
  <% end %>
  <p>
    <%= label_tag t('.method') %>
    <%= select_tag :method, options_for_select(%w[GET POST PUT PATCH DELETE], 'GET') %>
  </p>
  <%= submit_tag t('.create') %>
<% end %>

app/views/lecter/diagnosis/new.html.erb
<%= content_for :title, t('.title')  %>

<div class="container">
  <h2><%= t('.title') %></h2>

  <%= form_tag diagnosis_path do %>
    <% flash.each do |key, value| %>
      <div class="col-sm-2 col-form-label">
        <%= value %>
      </div>
    <% end %>
    <div class="row my-3">
      <%= label_tag t('.method'), nil, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm">
        <%= select_tag :method, options_for_select(Lecter::AVAILABLE_METHODS, Lecter::DEFAULT_METHOD) %>
      </div>
      <div class="col-sm gray">
        Choose one
      </div>
    </div>
    <div class="row my-3">
      <%= label_tag t('.endpoint'), nil, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm">
        <%= text_field_tag :endpoint, nil, class: 'form-control', placeholder: 'Endpoint' %>
      </div>
      <div class="col-sm gray">
        localhost:3000/posts
      </div>
    </div>
    <div class="row my-3">
      <%= label_tag t('.headers'), nil, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm">
        <%= text_field_tag :headers, nil, class: 'form-control', placeholder: 'Headers' %>
      </div>
      <div class="col-sm gray">
        content_type=text/html,accept=*/*
      </div>
    </div>
    <div class="row my-3">
      <%= label_tag t('.body_raw'), nil, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm">
        <%= text_area_tag :body_raw, nil, rows: 10, class: 'form-control', placeholder: 'Body(raw)' %>
      </div>
      <div class="col-sm gray">
        "post" => {
          "title" => "New title",
          "description" => "Desciption"
        }
      </div>
    </div>

    </p>
    <%= submit_tag t('.send'), class: 'btn btn-primary' %>
  <% end %>
</div>

<style>
  .gray {
      color: #727a82
  }
</style>